version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
          time: "00:00"
          timezone: "Etc/UTC"
      cooldown:
          default-days: 1
          include:
              - "*"
      commit-message:
          prefix: "chore"
      ignore:
          # dep
          - dependency-name: "es-toolkit"
          - dependency-name: "rollup-plugin-copy"
          - dependency-name: "srvx"
          - dependency-name: "ts-vista"
          # peer
          - dependency-name: "vite"
